### PR TITLE
Maps endpoint

### PR DESCRIPTION
**Pull request by RobLoweMOJ**
New maps endpoint using PHP. We will now need two API keys one in the footer.php thats used to load the map and markers (domain restricted). Another for the lookup. Server IP restricted.

### CODE REVIEW

**Review by wilson1000-MoJ — COMMENTED** [review]
Hey Rob, have you tested this implementation? All working well??

**Review by wilson1000-MoJ — COMMENTED** [review]
... I've noticed that the actions in the search-form.js (window.location) have been commented out

**Comment by RobLoweMOJ** [comment]
> ... I've noticed that the actions in the search-form.js (window.location) have been commented out

Yes i fixed this in a later commit. After i mistakenly left them commented out. If you go to files changed tab you can see they are not commented out.

**Comment by RobLoweMOJ** [comment]
> > ... I've noticed that the actions in the search-form.js (window.location) have been commented out
> 
> Yes i fixed this in a later commit. After i mistakenly left them commented out. If you go to files changed tab you can see they are not commented out. ha

also yes its working locally

**Pull request merged**
